apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-server
  labels:
    app: go-app
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: nainani344sumit/gomemlimit-exp:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 460Mi
            requests:
              memory: 460Mi
            